'use strict';

module.exports = {
  AirFlow: {
    0: 'auto',
    1: 'lowest',
    2: 'low',
    3: 'high',
    4: 'highest',
  },
  AirFlowNames: {
    auto: 0,
    lowest: 1,
    low: 2,
    high: 3,
    highest: 4,
  },
  HorizontalPosition: {
    0: 'auto',
    1: 'left-left',
    2: 'left-center',
    3: 'center-center',
    4: 'center-right',
    5: 'right-right',
    6: 'left-right',
    7: 'right-left',
  },
  HorizontalPositionNames: {
    auto: 0,
    'left-left': 1,
    'left-center': 2,
    'center-center': 3,
    'center-right': 4,
    'right-right': 5,
    'left-right': 6,
    'right-left': 7,
  },
  OperationMode: {
    0: 'auto',
    1: 'cool',
    2: 'heat',
    3: 'fan',
    4: 'dry',
  },
  OperationModeNames: {
    auto: 0,
    cool: 1,
    heat: 2,
    fan: 3,
    dry: 4,
  },
  VerticalPosition: {
    0: 'auto',
    1: 'highest',
    2: 'middle',
    3: 'normal',
    4: 'lowest',
  },
  VerticalPositionNames: {
    auto: 0,
    highest: 1,
    middle: 2,
    normal: 3,
    lowest: 4,
  },
};
